language: r
cache: packages
dist: bionic

os:
  - linux
  - osx

osx_image: xcode12.2

r:
  - oldrel
  - release

# Combinations that don't work in travis-ci
jobs:
  include:
    - r: 3.4
      os: linux
      warnings_are_errors: false

    - r: oldrel
      os: osx
      fortran: false
      

# r_binary_packages:
#   - modeltools
#   - Rdpack
#   - withr
#   - testthat
#   - rlang
#   - openssl
#   - xml2
#   - fansi

addons:    
  apt:
    packages:
      - libgsl-dev
      - libharfbuzz-dev
      - libfribidi-dev

  homebrew:
    packages:
      - gsl
      
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - NOT_CRAN=true
    - CRAN: http://cran.rstudio.com
    - MAKEFLAGS="-j 2"

r_check_args: '--run-donttest --run-dontrun --timings'

notifications:
  email: false

#before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'

after_success:
  - test $TRAVIS_OS_NAME = "linux" && test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov(type="all", quiet = FALSE)'
  
deploy:
  provider: script
  skip_cleanup: true
  script: Rscript -e 'remotes::install_github("r-lib/pkgdown");pkgdown::deploy_site_github(run_dont_run = TRUE)'
  on:
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = release
