language: R
cache: packages
sudo: true
dist: trusty

r:
- oldrel
- release
- devel

# work around temporary travis + R 3.5 bug
r_packages: devtools
            
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - NOT_CRAN=true

after_success:
  - Rscript -e 'covr::codecov()'

