language: r
cache: packages
fortran: false
sudo: false
dist: trusty

# matrix doesn't work
os:
  - linux
  - osx
  
r:
  - 3.1
  - oldrel
  - release


r_check_args: '--ignore-vignettes --no-examples'

# addons:
#   apt:
#     packages:
#       - libfreetype6

# work around temporary travis + R 3.5 bug
r_packages:
  - devtools
            
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - NOT_CRAN=true
    - CRAN: http://cran.rstudio.com

r_check_args: '--run-donttest --run-dontrun --timings'

  
before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

notifications:
  email: false
