language: R
cache: packages

os:
  - linux
  - osx
  
r:
  - oldrel
  - release

# Combinations that don't work in travis-ci
jobs:
  include:
    - r: 3.2
      os: linux
      dist: trusty
      warnings_are_errors: false


env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
    - NOT_CRAN=true
    - CRAN: http://cran.rstudio.com
    - MAKEFLAGS="-j 2"

r_check_args: '--run-donttest --run-dontrun --timings'

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

notifications:
  email: false

before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
deploy:
  provider: script
  skip_cleanup: true
  script: Rscript -e 'pkgdown::deploy_site_github(run_dont_run = TRUE)'
  on:
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_R_VERSION_STRING = release
    

  

