language: r
cache: packages
fortran: false
sudo: required

r:
- 3.0
- oldrel
- release


matrix:
  include:
    - os: linux
      dist: trusty
      before_install:
        - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes 
        - sudo apt-get --yes --force-yes update -qq 
        - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
        - Rscript -e 'update.packages(ask = FALSE)'
    - os: osx
      before_install:
        - sudo tlmgr update --self
        - Rscript -e 'update.packages(ask = FALSE)'
       
r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
     - libfreetype6


# work around temporary travis + R 3.5 bug
r_packages: devtools
            
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - NOT_CRAN=true

r_check_args: '--run-donttest --run-dontrun --timings'

  
