language: R
cache: packages
sudo: true
os:
  - linux
  - osx
  
dist: trusty

addons:
  apt:
    packages:
     - libfreetype6

r:
- 3.0
- oldrel
- release


# work around temporary travis + R 3.5 bug
r_packages: devtools
            
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - NOT_CRAN=true

r_check_args:
 - --run-donttest --run-dontrun --timings
 
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get --yes --force-yes update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev ; fi
  - Rscript -e 'update.packages(ask = FALSE)'
