#!/bin/sh
rm -f  config.* confdefs.h tests/testthat/*.pdf \
       src/*.o src/*.so src/Makevars src/config.h src/symbols.rds \
       inst/doc/*.blg inst/doc/*.bbl *-Ex.R \
       src/eaf/eaf \
       src/mo-tools/dominatedsets \
       src/mo-tools/epsilon \
       src/mo-tools/igd \
       src/mo-tools/ndsort \
       src/mo-tools/nondominated

rm -rf autom4te.cache
